trigger:
- master

jobs:
- job:
  displayName: Windows
  pool:
    vmImage: 'windows-latest'

  steps:
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      mkdir build
      cd build
      cmake -S .. -G "NMake Makefiles"
      cmake --build .
    displayName: 'Build'

- job:
  displayName: Linux
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: |
      mkdir build
      cd build
      cmake -S ..
      cmake --build .
    displayName: 'Build'
